/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Additional non-threat content verification information
 */
@JsonPropertyOrder({
  AdditionalAdvancedScanInformation.JSON_PROPERTY_CONTAINS_J_S_O_N,
  AdditionalAdvancedScanInformation.JSON_PROPERTY_CONTAINS_X_M_L,
  AdditionalAdvancedScanInformation.JSON_PROPERTY_CONTAINS_IMAGE,
  AdditionalAdvancedScanInformation.JSON_PROPERTY_HASH_S_H_A1,
  AdditionalAdvancedScanInformation.JSON_PROPERTY_RELEVANT_SUBFILE_NAME,
  AdditionalAdvancedScanInformation.JSON_PROPERTY_RELEVANT_SUBFILE_HASH_S_H_A1,
  AdditionalAdvancedScanInformation.JSON_PROPERTY_IS_AUTHENTICODE_SIGNED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T21:04:27.160244900-08:00[America/Los_Angeles]", comments = "Generator version: 7.12.0")
public class AdditionalAdvancedScanInformation {
  public static final String JSON_PROPERTY_CONTAINS_J_S_O_N = "ContainsJSON";
  @javax.annotation.Nullable
  private Boolean containsJSON;

  public static final String JSON_PROPERTY_CONTAINS_X_M_L = "ContainsXML";
  @javax.annotation.Nullable
  private Boolean containsXML;

  public static final String JSON_PROPERTY_CONTAINS_IMAGE = "ContainsImage";
  @javax.annotation.Nullable
  private Boolean containsImage;

  public static final String JSON_PROPERTY_HASH_S_H_A1 = "Hash_SHA1";
  @javax.annotation.Nullable
  private String hashSHA1;

  public static final String JSON_PROPERTY_RELEVANT_SUBFILE_NAME = "RelevantSubfileName";
  @javax.annotation.Nullable
  private String relevantSubfileName;

  public static final String JSON_PROPERTY_RELEVANT_SUBFILE_HASH_S_H_A1 = "RelevantSubfileHash_SHA1";
  @javax.annotation.Nullable
  private String relevantSubfileHashSHA1;

  public static final String JSON_PROPERTY_IS_AUTHENTICODE_SIGNED = "IsAuthenticodeSigned";
  @javax.annotation.Nullable
  private Boolean isAuthenticodeSigned;

  public AdditionalAdvancedScanInformation() { 
  }

  public AdditionalAdvancedScanInformation containsJSON(@javax.annotation.Nullable Boolean containsJSON) {
    this.containsJSON = containsJSON;
    return this;
  }

  /**
   * True if the input file contains JSON data, false otherwise; this is not a threat signal
   * @return containsJSON
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_J_S_O_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsJSON() {
    return containsJSON;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_J_S_O_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsJSON(@javax.annotation.Nullable Boolean containsJSON) {
    this.containsJSON = containsJSON;
  }


  public AdditionalAdvancedScanInformation containsXML(@javax.annotation.Nullable Boolean containsXML) {
    this.containsXML = containsXML;
    return this;
  }

  /**
   * True if the input file contains XML data, false otherwise; this is not a threat signal
   * @return containsXML
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_X_M_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsXML() {
    return containsXML;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_X_M_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsXML(@javax.annotation.Nullable Boolean containsXML) {
    this.containsXML = containsXML;
  }


  public AdditionalAdvancedScanInformation containsImage(@javax.annotation.Nullable Boolean containsImage) {
    this.containsImage = containsImage;
    return this;
  }

  /**
   * True if the input file contains an image
   * @return containsImage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsImage() {
    return containsImage;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsImage(@javax.annotation.Nullable Boolean containsImage) {
    this.containsImage = containsImage;
  }


  public AdditionalAdvancedScanInformation hashSHA1(@javax.annotation.Nullable String hashSHA1) {
    this.hashSHA1 = hashSHA1;
    return this;
  }

  /**
   * SHA1 hash of input file
   * @return hashSHA1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HASH_S_H_A1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHashSHA1() {
    return hashSHA1;
  }


  @JsonProperty(JSON_PROPERTY_HASH_S_H_A1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHashSHA1(@javax.annotation.Nullable String hashSHA1) {
    this.hashSHA1 = hashSHA1;
  }


  public AdditionalAdvancedScanInformation relevantSubfileName(@javax.annotation.Nullable String relevantSubfileName) {
    this.relevantSubfileName = relevantSubfileName;
    return this;
  }

  /**
   * Relevant subfile name in an archive format for identified threats, if any
   * @return relevantSubfileName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELEVANT_SUBFILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRelevantSubfileName() {
    return relevantSubfileName;
  }


  @JsonProperty(JSON_PROPERTY_RELEVANT_SUBFILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelevantSubfileName(@javax.annotation.Nullable String relevantSubfileName) {
    this.relevantSubfileName = relevantSubfileName;
  }


  public AdditionalAdvancedScanInformation relevantSubfileHashSHA1(@javax.annotation.Nullable String relevantSubfileHashSHA1) {
    this.relevantSubfileHashSHA1 = relevantSubfileHashSHA1;
    return this;
  }

  /**
   * SHA1 hash of relevant subfile name in an archive format for identified threats, if any
   * @return relevantSubfileHashSHA1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELEVANT_SUBFILE_HASH_S_H_A1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRelevantSubfileHashSHA1() {
    return relevantSubfileHashSHA1;
  }


  @JsonProperty(JSON_PROPERTY_RELEVANT_SUBFILE_HASH_S_H_A1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelevantSubfileHashSHA1(@javax.annotation.Nullable String relevantSubfileHashSHA1) {
    this.relevantSubfileHashSHA1 = relevantSubfileHashSHA1;
  }


  public AdditionalAdvancedScanInformation isAuthenticodeSigned(@javax.annotation.Nullable Boolean isAuthenticodeSigned) {
    this.isAuthenticodeSigned = isAuthenticodeSigned;
    return this;
  }

  /**
   * True if there is a valid Authenticode signature, False otherwise
   * @return isAuthenticodeSigned
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_AUTHENTICODE_SIGNED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsAuthenticodeSigned() {
    return isAuthenticodeSigned;
  }


  @JsonProperty(JSON_PROPERTY_IS_AUTHENTICODE_SIGNED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAuthenticodeSigned(@javax.annotation.Nullable Boolean isAuthenticodeSigned) {
    this.isAuthenticodeSigned = isAuthenticodeSigned;
  }


  /**
   * Return true if this AdditionalAdvancedScanInformation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalAdvancedScanInformation additionalAdvancedScanInformation = (AdditionalAdvancedScanInformation) o;
    return Objects.equals(this.containsJSON, additionalAdvancedScanInformation.containsJSON) &&
        Objects.equals(this.containsXML, additionalAdvancedScanInformation.containsXML) &&
        Objects.equals(this.containsImage, additionalAdvancedScanInformation.containsImage) &&
        Objects.equals(this.hashSHA1, additionalAdvancedScanInformation.hashSHA1) &&
        Objects.equals(this.relevantSubfileName, additionalAdvancedScanInformation.relevantSubfileName) &&
        Objects.equals(this.relevantSubfileHashSHA1, additionalAdvancedScanInformation.relevantSubfileHashSHA1) &&
        Objects.equals(this.isAuthenticodeSigned, additionalAdvancedScanInformation.isAuthenticodeSigned);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containsJSON, containsXML, containsImage, hashSHA1, relevantSubfileName, relevantSubfileHashSHA1, isAuthenticodeSigned);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalAdvancedScanInformation {\n");
    sb.append("    containsJSON: ").append(toIndentedString(containsJSON)).append("\n");
    sb.append("    containsXML: ").append(toIndentedString(containsXML)).append("\n");
    sb.append("    containsImage: ").append(toIndentedString(containsImage)).append("\n");
    sb.append("    hashSHA1: ").append(toIndentedString(hashSHA1)).append("\n");
    sb.append("    relevantSubfileName: ").append(toIndentedString(relevantSubfileName)).append("\n");
    sb.append("    relevantSubfileHashSHA1: ").append(toIndentedString(relevantSubfileHashSHA1)).append("\n");
    sb.append("    isAuthenticodeSigned: ").append(toIndentedString(isAuthenticodeSigned)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ContainsJSON` to the URL query string
    if (getContainsJSON() != null) {
      joiner.add(String.format("%sContainsJSON%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsJSON()))));
    }

    // add `ContainsXML` to the URL query string
    if (getContainsXML() != null) {
      joiner.add(String.format("%sContainsXML%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsXML()))));
    }

    // add `ContainsImage` to the URL query string
    if (getContainsImage() != null) {
      joiner.add(String.format("%sContainsImage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsImage()))));
    }

    // add `Hash_SHA1` to the URL query string
    if (getHashSHA1() != null) {
      joiner.add(String.format("%sHash_SHA1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHashSHA1()))));
    }

    // add `RelevantSubfileName` to the URL query string
    if (getRelevantSubfileName() != null) {
      joiner.add(String.format("%sRelevantSubfileName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRelevantSubfileName()))));
    }

    // add `RelevantSubfileHash_SHA1` to the URL query string
    if (getRelevantSubfileHashSHA1() != null) {
      joiner.add(String.format("%sRelevantSubfileHash_SHA1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRelevantSubfileHashSHA1()))));
    }

    // add `IsAuthenticodeSigned` to the URL query string
    if (getIsAuthenticodeSigned() != null) {
      joiner.add(String.format("%sIsAuthenticodeSigned%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsAuthenticodeSigned()))));
    }

    return joiner.toString();
  }
}

