/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Virus positively identified
 */
@JsonPropertyOrder({
  CloudStorageVirusFound.JSON_PROPERTY_FILE_NAME,
  CloudStorageVirusFound.JSON_PROPERTY_VIRUS_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T21:04:27.160244900-08:00[America/Los_Angeles]", comments = "Generator version: 7.12.0")
public class CloudStorageVirusFound {
  public static final String JSON_PROPERTY_FILE_NAME = "FileName";
  @javax.annotation.Nullable
  private String fileName;

  public static final String JSON_PROPERTY_VIRUS_NAME = "VirusName";
  @javax.annotation.Nullable
  private String virusName;

  public CloudStorageVirusFound() { 
  }

  public CloudStorageVirusFound fileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
    return this;
  }

  /**
   * Name of the file containing the virus
   * @return fileName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFileName() {
    return fileName;
  }


  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
  }


  public CloudStorageVirusFound virusName(@javax.annotation.Nullable String virusName) {
    this.virusName = virusName;
    return this;
  }

  /**
   * Name of the virus that was found
   * @return virusName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VIRUS_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVirusName() {
    return virusName;
  }


  @JsonProperty(JSON_PROPERTY_VIRUS_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVirusName(@javax.annotation.Nullable String virusName) {
    this.virusName = virusName;
  }


  /**
   * Return true if this CloudStorageVirusFound object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudStorageVirusFound cloudStorageVirusFound = (CloudStorageVirusFound) o;
    return Objects.equals(this.fileName, cloudStorageVirusFound.fileName) &&
        Objects.equals(this.virusName, cloudStorageVirusFound.virusName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, virusName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudStorageVirusFound {\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    virusName: ").append(toIndentedString(virusName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `FileName` to the URL query string
    if (getFileName() != null) {
      joiner.add(String.format("%sFileName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFileName()))));
    }

    // add `VirusName` to the URL query string
    if (getVirusName() != null) {
      joiner.add(String.format("%sVirusName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVirusName()))));
    }

    return joiner.toString();
  }
}

