/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AdditionalAdvancedScanInformation;
import org.openapitools.client.model.CloudStorageVirusFound;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Result of running an advanced virus scan on cloud storage
 */
@JsonPropertyOrder({
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_SUCCESSFUL,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CLEAN_RESULT,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_EXECUTABLE,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_INVALID_FILE,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_SCRIPT,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_PASSWORD_PROTECTED_FILE,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_RESTRICTED_FILE_FORMAT,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_MACROS,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_XML_EXTERNAL_ENTITIES,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_INSECURE_DESERIALIZATION,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_HTML,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_UNSAFE_ARCHIVE,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTAINS_OLE_EMBEDDED_OBJECT,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_VERIFIED_FILE_FORMAT,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_FOUND_VIRUSES,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_ERROR_DETAILED_DESCRIPTION,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_FILE_SIZE,
  CloudStorageAdvancedVirusScanResult.JSON_PROPERTY_CONTENT_INFORMATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T21:04:27.160244900-08:00[America/Los_Angeles]", comments = "Generator version: 7.12.0")
public class CloudStorageAdvancedVirusScanResult {
  public static final String JSON_PROPERTY_SUCCESSFUL = "Successful";
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String JSON_PROPERTY_CLEAN_RESULT = "CleanResult";
  @javax.annotation.Nullable
  private Boolean cleanResult;

  public static final String JSON_PROPERTY_CONTAINS_EXECUTABLE = "ContainsExecutable";
  @javax.annotation.Nullable
  private Boolean containsExecutable;

  public static final String JSON_PROPERTY_CONTAINS_INVALID_FILE = "ContainsInvalidFile";
  @javax.annotation.Nullable
  private Boolean containsInvalidFile;

  public static final String JSON_PROPERTY_CONTAINS_SCRIPT = "ContainsScript";
  @javax.annotation.Nullable
  private Boolean containsScript;

  public static final String JSON_PROPERTY_CONTAINS_PASSWORD_PROTECTED_FILE = "ContainsPasswordProtectedFile";
  @javax.annotation.Nullable
  private Boolean containsPasswordProtectedFile;

  public static final String JSON_PROPERTY_CONTAINS_RESTRICTED_FILE_FORMAT = "ContainsRestrictedFileFormat";
  @javax.annotation.Nullable
  private Boolean containsRestrictedFileFormat;

  public static final String JSON_PROPERTY_CONTAINS_MACROS = "ContainsMacros";
  @javax.annotation.Nullable
  private Boolean containsMacros;

  public static final String JSON_PROPERTY_CONTAINS_XML_EXTERNAL_ENTITIES = "ContainsXmlExternalEntities";
  @javax.annotation.Nullable
  private Boolean containsXmlExternalEntities;

  public static final String JSON_PROPERTY_CONTAINS_INSECURE_DESERIALIZATION = "ContainsInsecureDeserialization";
  @javax.annotation.Nullable
  private Boolean containsInsecureDeserialization;

  public static final String JSON_PROPERTY_CONTAINS_HTML = "ContainsHtml";
  @javax.annotation.Nullable
  private Boolean containsHtml;

  public static final String JSON_PROPERTY_CONTAINS_UNSAFE_ARCHIVE = "ContainsUnsafeArchive";
  @javax.annotation.Nullable
  private Boolean containsUnsafeArchive;

  public static final String JSON_PROPERTY_CONTAINS_OLE_EMBEDDED_OBJECT = "ContainsOleEmbeddedObject";
  @javax.annotation.Nullable
  private Boolean containsOleEmbeddedObject;

  public static final String JSON_PROPERTY_VERIFIED_FILE_FORMAT = "VerifiedFileFormat";
  @javax.annotation.Nullable
  private String verifiedFileFormat;

  public static final String JSON_PROPERTY_FOUND_VIRUSES = "FoundViruses";
  @javax.annotation.Nullable
  private List<CloudStorageVirusFound> foundViruses = new ArrayList<>();

  public static final String JSON_PROPERTY_ERROR_DETAILED_DESCRIPTION = "ErrorDetailedDescription";
  @javax.annotation.Nullable
  private String errorDetailedDescription;

  public static final String JSON_PROPERTY_FILE_SIZE = "FileSize";
  @javax.annotation.Nullable
  private Long fileSize;

  public static final String JSON_PROPERTY_CONTENT_INFORMATION = "ContentInformation";
  @javax.annotation.Nullable
  private AdditionalAdvancedScanInformation contentInformation;

  public CloudStorageAdvancedVirusScanResult() { 
  }

  public CloudStorageAdvancedVirusScanResult successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * True if the operation of retrieving the file, and scanning it were successfully completed, false if the file could not be downloaded from cloud storage, or if the file could not be scanned.  Note that successful completion does not mean the file is clean; for the output of the virus scanning operation itself, use the CleanResult and FoundViruses parameters.
   * @return successful
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSuccessful() {
    return successful;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public CloudStorageAdvancedVirusScanResult cleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
    return this;
  }

  /**
   * True if the scan contained no viruses, false otherwise
   * @return cleanResult
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLEAN_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCleanResult() {
    return cleanResult;
  }


  @JsonProperty(JSON_PROPERTY_CLEAN_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
  }


  public CloudStorageAdvancedVirusScanResult containsExecutable(@javax.annotation.Nullable Boolean containsExecutable) {
    this.containsExecutable = containsExecutable;
    return this;
  }

  /**
   * True if the scan contained an executable (application code), which can be a significant risk factor
   * @return containsExecutable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_EXECUTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsExecutable() {
    return containsExecutable;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_EXECUTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsExecutable(@javax.annotation.Nullable Boolean containsExecutable) {
    this.containsExecutable = containsExecutable;
  }


  public CloudStorageAdvancedVirusScanResult containsInvalidFile(@javax.annotation.Nullable Boolean containsInvalidFile) {
    this.containsInvalidFile = containsInvalidFile;
    return this;
  }

  /**
   * True if the scan contained an invalid file (such as a PDF that is not a valid PDF, Word Document that is not a valid Word Document, etc.), which can be a significant risk factor
   * @return containsInvalidFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_INVALID_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsInvalidFile() {
    return containsInvalidFile;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_INVALID_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsInvalidFile(@javax.annotation.Nullable Boolean containsInvalidFile) {
    this.containsInvalidFile = containsInvalidFile;
  }


  public CloudStorageAdvancedVirusScanResult containsScript(@javax.annotation.Nullable Boolean containsScript) {
    this.containsScript = containsScript;
    return this;
  }

  /**
   * True if the scan contained a script (such as a PHP script, Python script, etc.) which can be a significant risk factor
   * @return containsScript
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsScript() {
    return containsScript;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsScript(@javax.annotation.Nullable Boolean containsScript) {
    this.containsScript = containsScript;
  }


  public CloudStorageAdvancedVirusScanResult containsPasswordProtectedFile(@javax.annotation.Nullable Boolean containsPasswordProtectedFile) {
    this.containsPasswordProtectedFile = containsPasswordProtectedFile;
    return this;
  }

  /**
   * True if the scan contained a password protected or encrypted file, which can be a significant risk factor
   * @return containsPasswordProtectedFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_PASSWORD_PROTECTED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsPasswordProtectedFile() {
    return containsPasswordProtectedFile;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_PASSWORD_PROTECTED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsPasswordProtectedFile(@javax.annotation.Nullable Boolean containsPasswordProtectedFile) {
    this.containsPasswordProtectedFile = containsPasswordProtectedFile;
  }


  public CloudStorageAdvancedVirusScanResult containsRestrictedFileFormat(@javax.annotation.Nullable Boolean containsRestrictedFileFormat) {
    this.containsRestrictedFileFormat = containsRestrictedFileFormat;
    return this;
  }

  /**
   * True if the uploaded file is of a type that is not allowed based on the optional restrictFileTypes parameter, false otherwise; if restrictFileTypes is not set, this will always be false
   * @return containsRestrictedFileFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_RESTRICTED_FILE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsRestrictedFileFormat() {
    return containsRestrictedFileFormat;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_RESTRICTED_FILE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsRestrictedFileFormat(@javax.annotation.Nullable Boolean containsRestrictedFileFormat) {
    this.containsRestrictedFileFormat = containsRestrictedFileFormat;
  }


  public CloudStorageAdvancedVirusScanResult containsMacros(@javax.annotation.Nullable Boolean containsMacros) {
    this.containsMacros = containsMacros;
    return this;
  }

  /**
   * True if the uploaded file contains embedded Macros of other embedded threats within the document, which can be a significant risk factor
   * @return containsMacros
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_MACROS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsMacros() {
    return containsMacros;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_MACROS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsMacros(@javax.annotation.Nullable Boolean containsMacros) {
    this.containsMacros = containsMacros;
  }


  public CloudStorageAdvancedVirusScanResult containsXmlExternalEntities(@javax.annotation.Nullable Boolean containsXmlExternalEntities) {
    this.containsXmlExternalEntities = containsXmlExternalEntities;
    return this;
  }

  /**
   * True if the uploaded file contains embedded XML External Entity threats of other embedded threats within the document, which can be a significant risk factor
   * @return containsXmlExternalEntities
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_XML_EXTERNAL_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsXmlExternalEntities() {
    return containsXmlExternalEntities;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_XML_EXTERNAL_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsXmlExternalEntities(@javax.annotation.Nullable Boolean containsXmlExternalEntities) {
    this.containsXmlExternalEntities = containsXmlExternalEntities;
  }


  public CloudStorageAdvancedVirusScanResult containsInsecureDeserialization(@javax.annotation.Nullable Boolean containsInsecureDeserialization) {
    this.containsInsecureDeserialization = containsInsecureDeserialization;
    return this;
  }

  /**
   * True if the uploaded file contains embedded Insecure Deserialization threats of other embedded threats within the document, which can be a significant risk factor
   * @return containsInsecureDeserialization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_INSECURE_DESERIALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsInsecureDeserialization() {
    return containsInsecureDeserialization;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_INSECURE_DESERIALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsInsecureDeserialization(@javax.annotation.Nullable Boolean containsInsecureDeserialization) {
    this.containsInsecureDeserialization = containsInsecureDeserialization;
  }


  public CloudStorageAdvancedVirusScanResult containsHtml(@javax.annotation.Nullable Boolean containsHtml) {
    this.containsHtml = containsHtml;
    return this;
  }

  /**
   * True if the uploaded file contains HTML, which can be a significant risk factor
   * @return containsHtml
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_HTML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsHtml() {
    return containsHtml;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_HTML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsHtml(@javax.annotation.Nullable Boolean containsHtml) {
    this.containsHtml = containsHtml;
  }


  public CloudStorageAdvancedVirusScanResult containsUnsafeArchive(@javax.annotation.Nullable Boolean containsUnsafeArchive) {
    this.containsUnsafeArchive = containsUnsafeArchive;
    return this;
  }

  /**
   * True if the uploaded file contains unsafe archive (e.g. zip) content, such as a Zip Bomb, or other configurations of a zip file that could lead to an unsafe extraction
   * @return containsUnsafeArchive
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_UNSAFE_ARCHIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsUnsafeArchive() {
    return containsUnsafeArchive;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_UNSAFE_ARCHIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsUnsafeArchive(@javax.annotation.Nullable Boolean containsUnsafeArchive) {
    this.containsUnsafeArchive = containsUnsafeArchive;
  }


  public CloudStorageAdvancedVirusScanResult containsOleEmbeddedObject(@javax.annotation.Nullable Boolean containsOleEmbeddedObject) {
    this.containsOleEmbeddedObject = containsOleEmbeddedObject;
    return this;
  }

  /**
   * True if the uploaded file contains an OLE embedded object, which can be a significant risk factor
   * @return containsOleEmbeddedObject
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_OLE_EMBEDDED_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsOleEmbeddedObject() {
    return containsOleEmbeddedObject;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINS_OLE_EMBEDDED_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsOleEmbeddedObject(@javax.annotation.Nullable Boolean containsOleEmbeddedObject) {
    this.containsOleEmbeddedObject = containsOleEmbeddedObject;
  }


  public CloudStorageAdvancedVirusScanResult verifiedFileFormat(@javax.annotation.Nullable String verifiedFileFormat) {
    this.verifiedFileFormat = verifiedFileFormat;
    return this;
  }

  /**
   * For file format verification-supported file formats, the contents-verified file format of the file.  Null indicates that the file format is not supported for contents verification.  If a Virus or Malware is found, this field will always be set to Null.
   * @return verifiedFileFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERIFIED_FILE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVerifiedFileFormat() {
    return verifiedFileFormat;
  }


  @JsonProperty(JSON_PROPERTY_VERIFIED_FILE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerifiedFileFormat(@javax.annotation.Nullable String verifiedFileFormat) {
    this.verifiedFileFormat = verifiedFileFormat;
  }


  public CloudStorageAdvancedVirusScanResult foundViruses(@javax.annotation.Nullable List<CloudStorageVirusFound> foundViruses) {
    this.foundViruses = foundViruses;
    return this;
  }

  public CloudStorageAdvancedVirusScanResult addFoundVirusesItem(CloudStorageVirusFound foundVirusesItem) {
    if (this.foundViruses == null) {
      this.foundViruses = new ArrayList<>();
    }
    this.foundViruses.add(foundVirusesItem);
    return this;
  }

  /**
   * Array of viruses found, if any
   * @return foundViruses
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOUND_VIRUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<CloudStorageVirusFound> getFoundViruses() {
    return foundViruses;
  }


  @JsonProperty(JSON_PROPERTY_FOUND_VIRUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFoundViruses(@javax.annotation.Nullable List<CloudStorageVirusFound> foundViruses) {
    this.foundViruses = foundViruses;
  }


  public CloudStorageAdvancedVirusScanResult errorDetailedDescription(@javax.annotation.Nullable String errorDetailedDescription) {
    this.errorDetailedDescription = errorDetailedDescription;
    return this;
  }

  /**
   * Detailed error message if the operation was not successful
   * @return errorDetailedDescription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DETAILED_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorDetailedDescription() {
    return errorDetailedDescription;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DETAILED_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorDetailedDescription(@javax.annotation.Nullable String errorDetailedDescription) {
    this.errorDetailedDescription = errorDetailedDescription;
  }


  public CloudStorageAdvancedVirusScanResult fileSize(@javax.annotation.Nullable Long fileSize) {
    this.fileSize = fileSize;
    return this;
  }

  /**
   * Size in bytes of the file that was retrieved and scanned
   * @return fileSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getFileSize() {
    return fileSize;
  }


  @JsonProperty(JSON_PROPERTY_FILE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileSize(@javax.annotation.Nullable Long fileSize) {
    this.fileSize = fileSize;
  }


  public CloudStorageAdvancedVirusScanResult contentInformation(@javax.annotation.Nullable AdditionalAdvancedScanInformation contentInformation) {
    this.contentInformation = contentInformation;
    return this;
  }

  /**
   * Get contentInformation
   * @return contentInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AdditionalAdvancedScanInformation getContentInformation() {
    return contentInformation;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentInformation(@javax.annotation.Nullable AdditionalAdvancedScanInformation contentInformation) {
    this.contentInformation = contentInformation;
  }


  /**
   * Return true if this CloudStorageAdvancedVirusScanResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudStorageAdvancedVirusScanResult cloudStorageAdvancedVirusScanResult = (CloudStorageAdvancedVirusScanResult) o;
    return Objects.equals(this.successful, cloudStorageAdvancedVirusScanResult.successful) &&
        Objects.equals(this.cleanResult, cloudStorageAdvancedVirusScanResult.cleanResult) &&
        Objects.equals(this.containsExecutable, cloudStorageAdvancedVirusScanResult.containsExecutable) &&
        Objects.equals(this.containsInvalidFile, cloudStorageAdvancedVirusScanResult.containsInvalidFile) &&
        Objects.equals(this.containsScript, cloudStorageAdvancedVirusScanResult.containsScript) &&
        Objects.equals(this.containsPasswordProtectedFile, cloudStorageAdvancedVirusScanResult.containsPasswordProtectedFile) &&
        Objects.equals(this.containsRestrictedFileFormat, cloudStorageAdvancedVirusScanResult.containsRestrictedFileFormat) &&
        Objects.equals(this.containsMacros, cloudStorageAdvancedVirusScanResult.containsMacros) &&
        Objects.equals(this.containsXmlExternalEntities, cloudStorageAdvancedVirusScanResult.containsXmlExternalEntities) &&
        Objects.equals(this.containsInsecureDeserialization, cloudStorageAdvancedVirusScanResult.containsInsecureDeserialization) &&
        Objects.equals(this.containsHtml, cloudStorageAdvancedVirusScanResult.containsHtml) &&
        Objects.equals(this.containsUnsafeArchive, cloudStorageAdvancedVirusScanResult.containsUnsafeArchive) &&
        Objects.equals(this.containsOleEmbeddedObject, cloudStorageAdvancedVirusScanResult.containsOleEmbeddedObject) &&
        Objects.equals(this.verifiedFileFormat, cloudStorageAdvancedVirusScanResult.verifiedFileFormat) &&
        Objects.equals(this.foundViruses, cloudStorageAdvancedVirusScanResult.foundViruses) &&
        Objects.equals(this.errorDetailedDescription, cloudStorageAdvancedVirusScanResult.errorDetailedDescription) &&
        Objects.equals(this.fileSize, cloudStorageAdvancedVirusScanResult.fileSize) &&
        Objects.equals(this.contentInformation, cloudStorageAdvancedVirusScanResult.contentInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, cleanResult, containsExecutable, containsInvalidFile, containsScript, containsPasswordProtectedFile, containsRestrictedFileFormat, containsMacros, containsXmlExternalEntities, containsInsecureDeserialization, containsHtml, containsUnsafeArchive, containsOleEmbeddedObject, verifiedFileFormat, foundViruses, errorDetailedDescription, fileSize, contentInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudStorageAdvancedVirusScanResult {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    cleanResult: ").append(toIndentedString(cleanResult)).append("\n");
    sb.append("    containsExecutable: ").append(toIndentedString(containsExecutable)).append("\n");
    sb.append("    containsInvalidFile: ").append(toIndentedString(containsInvalidFile)).append("\n");
    sb.append("    containsScript: ").append(toIndentedString(containsScript)).append("\n");
    sb.append("    containsPasswordProtectedFile: ").append(toIndentedString(containsPasswordProtectedFile)).append("\n");
    sb.append("    containsRestrictedFileFormat: ").append(toIndentedString(containsRestrictedFileFormat)).append("\n");
    sb.append("    containsMacros: ").append(toIndentedString(containsMacros)).append("\n");
    sb.append("    containsXmlExternalEntities: ").append(toIndentedString(containsXmlExternalEntities)).append("\n");
    sb.append("    containsInsecureDeserialization: ").append(toIndentedString(containsInsecureDeserialization)).append("\n");
    sb.append("    containsHtml: ").append(toIndentedString(containsHtml)).append("\n");
    sb.append("    containsUnsafeArchive: ").append(toIndentedString(containsUnsafeArchive)).append("\n");
    sb.append("    containsOleEmbeddedObject: ").append(toIndentedString(containsOleEmbeddedObject)).append("\n");
    sb.append("    verifiedFileFormat: ").append(toIndentedString(verifiedFileFormat)).append("\n");
    sb.append("    foundViruses: ").append(toIndentedString(foundViruses)).append("\n");
    sb.append("    errorDetailedDescription: ").append(toIndentedString(errorDetailedDescription)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    contentInformation: ").append(toIndentedString(contentInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `Successful` to the URL query string
    if (getSuccessful() != null) {
      joiner.add(String.format("%sSuccessful%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuccessful()))));
    }

    // add `CleanResult` to the URL query string
    if (getCleanResult() != null) {
      joiner.add(String.format("%sCleanResult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCleanResult()))));
    }

    // add `ContainsExecutable` to the URL query string
    if (getContainsExecutable() != null) {
      joiner.add(String.format("%sContainsExecutable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsExecutable()))));
    }

    // add `ContainsInvalidFile` to the URL query string
    if (getContainsInvalidFile() != null) {
      joiner.add(String.format("%sContainsInvalidFile%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsInvalidFile()))));
    }

    // add `ContainsScript` to the URL query string
    if (getContainsScript() != null) {
      joiner.add(String.format("%sContainsScript%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsScript()))));
    }

    // add `ContainsPasswordProtectedFile` to the URL query string
    if (getContainsPasswordProtectedFile() != null) {
      joiner.add(String.format("%sContainsPasswordProtectedFile%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsPasswordProtectedFile()))));
    }

    // add `ContainsRestrictedFileFormat` to the URL query string
    if (getContainsRestrictedFileFormat() != null) {
      joiner.add(String.format("%sContainsRestrictedFileFormat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsRestrictedFileFormat()))));
    }

    // add `ContainsMacros` to the URL query string
    if (getContainsMacros() != null) {
      joiner.add(String.format("%sContainsMacros%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsMacros()))));
    }

    // add `ContainsXmlExternalEntities` to the URL query string
    if (getContainsXmlExternalEntities() != null) {
      joiner.add(String.format("%sContainsXmlExternalEntities%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsXmlExternalEntities()))));
    }

    // add `ContainsInsecureDeserialization` to the URL query string
    if (getContainsInsecureDeserialization() != null) {
      joiner.add(String.format("%sContainsInsecureDeserialization%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsInsecureDeserialization()))));
    }

    // add `ContainsHtml` to the URL query string
    if (getContainsHtml() != null) {
      joiner.add(String.format("%sContainsHtml%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsHtml()))));
    }

    // add `ContainsUnsafeArchive` to the URL query string
    if (getContainsUnsafeArchive() != null) {
      joiner.add(String.format("%sContainsUnsafeArchive%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsUnsafeArchive()))));
    }

    // add `ContainsOleEmbeddedObject` to the URL query string
    if (getContainsOleEmbeddedObject() != null) {
      joiner.add(String.format("%sContainsOleEmbeddedObject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsOleEmbeddedObject()))));
    }

    // add `VerifiedFileFormat` to the URL query string
    if (getVerifiedFileFormat() != null) {
      joiner.add(String.format("%sVerifiedFileFormat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerifiedFileFormat()))));
    }

    // add `FoundViruses` to the URL query string
    if (getFoundViruses() != null) {
      for (int i = 0; i < getFoundViruses().size(); i++) {
        if (getFoundViruses().get(i) != null) {
          joiner.add(getFoundViruses().get(i).toUrlQueryString(String.format("%sFoundViruses%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `ErrorDetailedDescription` to the URL query string
    if (getErrorDetailedDescription() != null) {
      joiner.add(String.format("%sErrorDetailedDescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorDetailedDescription()))));
    }

    // add `FileSize` to the URL query string
    if (getFileSize() != null) {
      joiner.add(String.format("%sFileSize%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFileSize()))));
    }

    // add `ContentInformation` to the URL query string
    if (getContentInformation() != null) {
      joiner.add(getContentInformation().toUrlQueryString(prefix + "ContentInformation" + suffix));
    }

    return joiner.toString();
  }
}

