/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.CloudStorageAdvancedVirusScanResult;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Status of the scan cloud storage job
 */
@JsonPropertyOrder({
  ScanCloudStorageJobStatusResult.JSON_PROPERTY_SUCCESSFUL,
  ScanCloudStorageJobStatusResult.JSON_PROPERTY_ASYNC_JOB_STATUS,
  ScanCloudStorageJobStatusResult.JSON_PROPERTY_ASYNC_JOB_I_D,
  ScanCloudStorageJobStatusResult.JSON_PROPERTY_RESULT,
  ScanCloudStorageJobStatusResult.JSON_PROPERTY_JOB_DURATION,
  ScanCloudStorageJobStatusResult.JSON_PROPERTY_ERROR_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T21:04:27.160244900-08:00[America/Los_Angeles]", comments = "Generator version: 7.12.0")
public class ScanCloudStorageJobStatusResult {
  public static final String JSON_PROPERTY_SUCCESSFUL = "Successful";
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String JSON_PROPERTY_ASYNC_JOB_STATUS = "AsyncJobStatus";
  @javax.annotation.Nullable
  private String asyncJobStatus;

  public static final String JSON_PROPERTY_ASYNC_JOB_I_D = "AsyncJobID";
  @javax.annotation.Nullable
  private String asyncJobID;

  public static final String JSON_PROPERTY_RESULT = "Result";
  @javax.annotation.Nullable
  private CloudStorageAdvancedVirusScanResult result;

  public static final String JSON_PROPERTY_JOB_DURATION = "JobDuration";
  @javax.annotation.Nullable
  private String jobDuration;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "ErrorMessage";
  @javax.annotation.Nullable
  private String errorMessage;

  public ScanCloudStorageJobStatusResult() { 
  }

  public ScanCloudStorageJobStatusResult successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * Tru eif the operation to check the status of the job was successful, false otherwise
   * @return successful
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSuccessful() {
    return successful;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public ScanCloudStorageJobStatusResult asyncJobStatus(@javax.annotation.Nullable String asyncJobStatus) {
    this.asyncJobStatus = asyncJobStatus;
    return this;
  }

  /**
   * Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
   * @return asyncJobStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASYNC_JOB_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAsyncJobStatus() {
    return asyncJobStatus;
  }


  @JsonProperty(JSON_PROPERTY_ASYNC_JOB_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsyncJobStatus(@javax.annotation.Nullable String asyncJobStatus) {
    this.asyncJobStatus = asyncJobStatus;
  }


  public ScanCloudStorageJobStatusResult asyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
    return this;
  }

  /**
   * Job ID of the async batch job
   * @return asyncJobID
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASYNC_JOB_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAsyncJobID() {
    return asyncJobID;
  }


  @JsonProperty(JSON_PROPERTY_ASYNC_JOB_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
  }


  public ScanCloudStorageJobStatusResult result(@javax.annotation.Nullable CloudStorageAdvancedVirusScanResult result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CloudStorageAdvancedVirusScanResult getResult() {
    return result;
  }


  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(@javax.annotation.Nullable CloudStorageAdvancedVirusScanResult result) {
    this.result = result;
  }


  public ScanCloudStorageJobStatusResult jobDuration(@javax.annotation.Nullable String jobDuration) {
    this.jobDuration = jobDuration;
    return this;
  }

  /**
   * Duration of a completed job
   * @return jobDuration
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getJobDuration() {
    return jobDuration;
  }


  @JsonProperty(JSON_PROPERTY_JOB_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobDuration(@javax.annotation.Nullable String jobDuration) {
    this.jobDuration = jobDuration;
  }


  public ScanCloudStorageJobStatusResult errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Error message (if any)
   * @return errorMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorMessage() {
    return errorMessage;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }


  /**
   * Return true if this ScanCloudStorageJobStatusResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanCloudStorageJobStatusResult scanCloudStorageJobStatusResult = (ScanCloudStorageJobStatusResult) o;
    return Objects.equals(this.successful, scanCloudStorageJobStatusResult.successful) &&
        Objects.equals(this.asyncJobStatus, scanCloudStorageJobStatusResult.asyncJobStatus) &&
        Objects.equals(this.asyncJobID, scanCloudStorageJobStatusResult.asyncJobID) &&
        Objects.equals(this.result, scanCloudStorageJobStatusResult.result) &&
        Objects.equals(this.jobDuration, scanCloudStorageJobStatusResult.jobDuration) &&
        Objects.equals(this.errorMessage, scanCloudStorageJobStatusResult.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, asyncJobStatus, asyncJobID, result, jobDuration, errorMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanCloudStorageJobStatusResult {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    asyncJobStatus: ").append(toIndentedString(asyncJobStatus)).append("\n");
    sb.append("    asyncJobID: ").append(toIndentedString(asyncJobID)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    jobDuration: ").append(toIndentedString(jobDuration)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `Successful` to the URL query string
    if (getSuccessful() != null) {
      joiner.add(String.format("%sSuccessful%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuccessful()))));
    }

    // add `AsyncJobStatus` to the URL query string
    if (getAsyncJobStatus() != null) {
      joiner.add(String.format("%sAsyncJobStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAsyncJobStatus()))));
    }

    // add `AsyncJobID` to the URL query string
    if (getAsyncJobID() != null) {
      joiner.add(String.format("%sAsyncJobID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAsyncJobID()))));
    }

    // add `Result` to the URL query string
    if (getResult() != null) {
      joiner.add(getResult().toUrlQueryString(prefix + "Result" + suffix));
    }

    // add `JobDuration` to the URL query string
    if (getJobDuration() != null) {
      joiner.add(String.format("%sJobDuration%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getJobDuration()))));
    }

    // add `ErrorMessage` to the URL query string
    if (getErrorMessage() != null) {
      joiner.add(String.format("%sErrorMessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorMessage()))));
    }

    return joiner.toString();
  }
}

