/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Result of performing a convert documentbatch job operation
 */
@JsonPropertyOrder({
  ScanCloudStorageBatchJobCreateResult.JSON_PROPERTY_SUCCESSFUL,
  ScanCloudStorageBatchJobCreateResult.JSON_PROPERTY_ASYNC_JOB_I_D
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T21:04:27.160244900-08:00[America/Los_Angeles]", comments = "Generator version: 7.12.0")
public class ScanCloudStorageBatchJobCreateResult {
  public static final String JSON_PROPERTY_SUCCESSFUL = "Successful";
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String JSON_PROPERTY_ASYNC_JOB_I_D = "AsyncJobID";
  @javax.annotation.Nullable
  private String asyncJobID;

  public ScanCloudStorageBatchJobCreateResult() { 
  }

  public ScanCloudStorageBatchJobCreateResult successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * True if successful, false otherwise
   * @return successful
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSuccessful() {
    return successful;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public ScanCloudStorageBatchJobCreateResult asyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
    return this;
  }

  /**
   * When creating a job, an Async Job ID is returned.  Use the GetAsyncJobStatus API to check on the status of this job using the AsyncJobID and get the result when it finishes
   * @return asyncJobID
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASYNC_JOB_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAsyncJobID() {
    return asyncJobID;
  }


  @JsonProperty(JSON_PROPERTY_ASYNC_JOB_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsyncJobID(@javax.annotation.Nullable String asyncJobID) {
    this.asyncJobID = asyncJobID;
  }


  /**
   * Return true if this ScanCloudStorageBatchJobCreateResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanCloudStorageBatchJobCreateResult scanCloudStorageBatchJobCreateResult = (ScanCloudStorageBatchJobCreateResult) o;
    return Objects.equals(this.successful, scanCloudStorageBatchJobCreateResult.successful) &&
        Objects.equals(this.asyncJobID, scanCloudStorageBatchJobCreateResult.asyncJobID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, asyncJobID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanCloudStorageBatchJobCreateResult {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    asyncJobID: ").append(toIndentedString(asyncJobID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `Successful` to the URL query string
    if (getSuccessful() != null) {
      joiner.add(String.format("%sSuccessful%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuccessful()))));
    }

    // add `AsyncJobID` to the URL query string
    if (getAsyncJobID() != null) {
      joiner.add(String.format("%sAsyncJobID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAsyncJobID()))));
    }

    return joiner.toString();
  }
}

