/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.VirusFound;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Result of running a website scan
 */
@JsonPropertyOrder({
  WebsiteScanResult.JSON_PROPERTY_CLEAN_RESULT,
  WebsiteScanResult.JSON_PROPERTY_WEBSITE_THREAT_TYPE,
  WebsiteScanResult.JSON_PROPERTY_FOUND_VIRUSES,
  WebsiteScanResult.JSON_PROPERTY_WEBSITE_HTTP_RESPONSE_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-27T21:04:27.160244900-08:00[America/Los_Angeles]", comments = "Generator version: 7.12.0")
public class WebsiteScanResult {
  public static final String JSON_PROPERTY_CLEAN_RESULT = "CleanResult";
  @javax.annotation.Nullable
  private Boolean cleanResult;

  /**
   * Type of threat returned; can be None, Malware, ForcedDownload or Phishing
   */
  public enum WebsiteThreatTypeEnum {
    NONE(String.valueOf("None")),
    
    MALWARE(String.valueOf("Malware")),
    
    PHISHING(String.valueOf("Phishing")),
    
    FORCED_DOWNLOAD(String.valueOf("ForcedDownload")),
    
    UNABLE_TO_CONNECT(String.valueOf("UnableToConnect"));

    private String value;

    WebsiteThreatTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WebsiteThreatTypeEnum fromValue(String value) {
      for (WebsiteThreatTypeEnum b : WebsiteThreatTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_WEBSITE_THREAT_TYPE = "WebsiteThreatType";
  @javax.annotation.Nullable
  private WebsiteThreatTypeEnum websiteThreatType;

  public static final String JSON_PROPERTY_FOUND_VIRUSES = "FoundViruses";
  @javax.annotation.Nullable
  private List<VirusFound> foundViruses = new ArrayList<>();

  public static final String JSON_PROPERTY_WEBSITE_HTTP_RESPONSE_CODE = "WebsiteHttpResponseCode";
  @javax.annotation.Nullable
  private Integer websiteHttpResponseCode;

  public WebsiteScanResult() { 
  }

  public WebsiteScanResult cleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
    return this;
  }

  /**
   * True if the scan contained no threats, false otherwise
   * @return cleanResult
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLEAN_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCleanResult() {
    return cleanResult;
  }


  @JsonProperty(JSON_PROPERTY_CLEAN_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCleanResult(@javax.annotation.Nullable Boolean cleanResult) {
    this.cleanResult = cleanResult;
  }


  public WebsiteScanResult websiteThreatType(@javax.annotation.Nullable WebsiteThreatTypeEnum websiteThreatType) {
    this.websiteThreatType = websiteThreatType;
    return this;
  }

  /**
   * Type of threat returned; can be None, Malware, ForcedDownload or Phishing
   * @return websiteThreatType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBSITE_THREAT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebsiteThreatTypeEnum getWebsiteThreatType() {
    return websiteThreatType;
  }


  @JsonProperty(JSON_PROPERTY_WEBSITE_THREAT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebsiteThreatType(@javax.annotation.Nullable WebsiteThreatTypeEnum websiteThreatType) {
    this.websiteThreatType = websiteThreatType;
  }


  public WebsiteScanResult foundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
    return this;
  }

  public WebsiteScanResult addFoundVirusesItem(VirusFound foundVirusesItem) {
    if (this.foundViruses == null) {
      this.foundViruses = new ArrayList<>();
    }
    this.foundViruses.add(foundVirusesItem);
    return this;
  }

  /**
   * Array of viruses found, if any
   * @return foundViruses
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOUND_VIRUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<VirusFound> getFoundViruses() {
    return foundViruses;
  }


  @JsonProperty(JSON_PROPERTY_FOUND_VIRUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFoundViruses(@javax.annotation.Nullable List<VirusFound> foundViruses) {
    this.foundViruses = foundViruses;
  }


  public WebsiteScanResult websiteHttpResponseCode(@javax.annotation.Nullable Integer websiteHttpResponseCode) {
    this.websiteHttpResponseCode = websiteHttpResponseCode;
    return this;
  }

  /**
   * The remote server URL HTTP reasponse code; useful for debugging issues with scanning; typically if the remote server returns a 200 or 300-series code this means a successful response, while a 400 or 500 series code would represent an error returned from the remote server for the provided URL.
   * @return websiteHttpResponseCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBSITE_HTTP_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getWebsiteHttpResponseCode() {
    return websiteHttpResponseCode;
  }


  @JsonProperty(JSON_PROPERTY_WEBSITE_HTTP_RESPONSE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebsiteHttpResponseCode(@javax.annotation.Nullable Integer websiteHttpResponseCode) {
    this.websiteHttpResponseCode = websiteHttpResponseCode;
  }


  /**
   * Return true if this WebsiteScanResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebsiteScanResult websiteScanResult = (WebsiteScanResult) o;
    return Objects.equals(this.cleanResult, websiteScanResult.cleanResult) &&
        Objects.equals(this.websiteThreatType, websiteScanResult.websiteThreatType) &&
        Objects.equals(this.foundViruses, websiteScanResult.foundViruses) &&
        Objects.equals(this.websiteHttpResponseCode, websiteScanResult.websiteHttpResponseCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cleanResult, websiteThreatType, foundViruses, websiteHttpResponseCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebsiteScanResult {\n");
    sb.append("    cleanResult: ").append(toIndentedString(cleanResult)).append("\n");
    sb.append("    websiteThreatType: ").append(toIndentedString(websiteThreatType)).append("\n");
    sb.append("    foundViruses: ").append(toIndentedString(foundViruses)).append("\n");
    sb.append("    websiteHttpResponseCode: ").append(toIndentedString(websiteHttpResponseCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `CleanResult` to the URL query string
    if (getCleanResult() != null) {
      joiner.add(String.format("%sCleanResult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCleanResult()))));
    }

    // add `WebsiteThreatType` to the URL query string
    if (getWebsiteThreatType() != null) {
      joiner.add(String.format("%sWebsiteThreatType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebsiteThreatType()))));
    }

    // add `FoundViruses` to the URL query string
    if (getFoundViruses() != null) {
      for (int i = 0; i < getFoundViruses().size(); i++) {
        if (getFoundViruses().get(i) != null) {
          joiner.add(getFoundViruses().get(i).toUrlQueryString(String.format("%sFoundViruses%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `WebsiteHttpResponseCode` to the URL query string
    if (getWebsiteHttpResponseCode() != null) {
      joiner.add(String.format("%sWebsiteHttpResponseCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebsiteHttpResponseCode()))));
    }

    return joiner.toString();
  }
}

