/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdditionalAdvancedScanInformation
 */
class AdditionalAdvancedScanInformationTest {
    private final AdditionalAdvancedScanInformation model = new AdditionalAdvancedScanInformation();

    /**
     * Model tests for AdditionalAdvancedScanInformation
     */
    @Test
    void testAdditionalAdvancedScanInformation() {
        // TODO: test AdditionalAdvancedScanInformation
    }

    /**
     * Test the property 'containsJSON'
     */
    @Test
    void containsJSONTest() {
        // TODO: test containsJSON
    }

    /**
     * Test the property 'containsXML'
     */
    @Test
    void containsXMLTest() {
        // TODO: test containsXML
    }

    /**
     * Test the property 'containsImage'
     */
    @Test
    void containsImageTest() {
        // TODO: test containsImage
    }

    /**
     * Test the property 'hashSHA1'
     */
    @Test
    void hashSHA1Test() {
        // TODO: test hashSHA1
    }

    /**
     * Test the property 'relevantSubfileName'
     */
    @Test
    void relevantSubfileNameTest() {
        // TODO: test relevantSubfileName
    }

    /**
     * Test the property 'relevantSubfileHashSHA1'
     */
    @Test
    void relevantSubfileHashSHA1Test() {
        // TODO: test relevantSubfileHashSHA1
    }

    /**
     * Test the property 'isAuthenticodeSigned'
     */
    @Test
    void isAuthenticodeSignedTest() {
        // TODO: test isAuthenticodeSigned
    }

}
