/*
 * virusapi
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.client.model.CloudStorageAdvancedVirusScanResult;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScanCloudStorageJobStatusResult
 */
class ScanCloudStorageJobStatusResultTest {
    private final ScanCloudStorageJobStatusResult model = new ScanCloudStorageJobStatusResult();

    /**
     * Model tests for ScanCloudStorageJobStatusResult
     */
    @Test
    void testScanCloudStorageJobStatusResult() {
        // TODO: test ScanCloudStorageJobStatusResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'asyncJobStatus'
     */
    @Test
    void asyncJobStatusTest() {
        // TODO: test asyncJobStatus
    }

    /**
     * Test the property 'asyncJobID'
     */
    @Test
    void asyncJobIDTest() {
        // TODO: test asyncJobID
    }

    /**
     * Test the property 'result'
     */
    @Test
    void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'jobDuration'
     */
    @Test
    void jobDurationTest() {
        // TODO: test jobDuration
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    void errorMessageTest() {
        // TODO: test errorMessage
    }

}
